name: Publish to test.pypi.org
on:
  - push

jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build wheel and sdist
        run: uv build

      - name: Upload dists
        uses: actions/upload-artifact@v4
        with:
          name: vmigration-helper-artifacts
          path: ./dist/
          retention-days: 2
          if-no-files-found: error

  publish:
    # NOTE that this will not publish to the production PyPI. It will only publish to the test PyPI.
    name: Test publishing to test.pypi.org
    runs-on: ubuntu-latest

    # Only publish when a tag starting with "v" is pushed, e.g., "v1.0.0"
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build
    environment:
      name: testpypi
      url: https://test.pypi.org/project/vmigration-helper/
    steps:
      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: vmigration-helper-artifacts
          path: ./dist/

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true
