name: Publish to test.pypi.org
on:
  - push

jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Install prereqs
        run: poetry install
      - name: Build
        run: poetry build
      - name: Upload dists
        uses: actions/upload-artifact@v3
        with:
          name: vmigration-helper-artifacts
          path: ./dist/
          retention-days: 2
          if-no-files-found: error
  publish:
    name: Test publishing to test.pypi.org
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build
    environment:
      name: testpypi
      url: https://test.pypi.org/project/vmigration-helper/
    steps:
      - name: Download dists
        uses: actions/download-artifact@v3
        with:
          name: vmigration-helper-artifacts
          path: ./dist/
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true
